/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

#define CLK_HZ 4000000
#define OPS_PER_FOR 3
#define MILLIS_IN_S 1000
#define BLINK_DELAY_MS 1000

int main(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOAEN;
	GPIOB->MODER |= 1 << 5 * 2;
	GPIOA->MODER |= 1 << 8 * 2;


	GPIOB->ODR ^= GPIO_ODR_OD5;

	/* Loop forever */
	for (;;) {
		GPIOA->ODR ^= GPIO_ODR_OD8;
		for(uint32_t i = 0; i < (BLINK_DELAY_MS * (CLK_HZ/OPS_PER_FOR) / MILLIS_IN_S); i++);
	}
}
